# azure pipeline config
# YAML schema reference:
# https://aka.ms/yaml

# trigger:
# - master

name: build_and_test
resources:
  containers:
  - container: debug
    image: ruffsl/navigation2:master.debug
    # options: "-v /usr/bin/docker:/tmp/docker:ro"
  - container: release
    image: ruffsl/navigation2:master.release
    # options: "-v /usr/bin/docker:/tmp/docker:ro"

variables:
- template: variables/common.yml
- name: CACHE_NONCE
  value: "Release"
- name: OVERLAY_MIXINS
  value: "release ccache"
- name: UNDERLAY_MIXINS
  value: "release ccache"

stages:
# - stage: Build
#   jobs:
#   - template: jobs/build.yml
#     parameters:
#       container: release
- stage: Test
  jobs:
  - template: jobs/test.yml
    parameters:
      container: release