# azure pipeline config
# YAML schema reference:
# https://aka.ms/yaml

# trigger:
# - master

name: build_and_test
resources:
  containers:
  - container: debug
    image: ruffsl/navigation2:master.debug
  - container: release
    image: ruffsl/navigation2:master.release

variables:
- template: variables/common.yml

stages:
- stage: Build
  jobs:
  - template: jobs/build.yml
    parameters:
      container: release
- stage: Test
  jobs:
  - template: jobs/test.yml
    parameters:
      container: release